### ISSUE TITLE
pip install iceberg_seals.search error

### ISSUE THREAD

**Issue by bspitzbart** [iceberg-project/Seals#58]
I installed iceberg_seals.search with: 
virtualenv seals
source seals/bin/activate
module load python3
module load cuda
pip3 install iceberg_seals.search
iceberg_seals.tiling --help

And get:
(seals) [bspitz@login018 ~]$ iceberg_seals.tiling --help
Traceback (most recent call last):
  File "/opt/packages/python/Python-3.5.2-icc-mkl/lib/python3.5/site-packages/numpy-1.12.0b1-py3.5-linux-x86_64.egg/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bspitz/seals/bin/iceberg_seals.tiling", line 8, in <module>
    from iceberg_seals.search.tiling.tile_raster import parse_args, tile_raster
  File "/home/bspitz/seals/lib/python3.5/site-packages/iceberg_seals/search/tiling/tile_raster.py", line 16, in <module>
    import numpy as np
  File "/opt/packages/python/Python-3.5.2-icc-mkl/lib/python3.5/site-packages/numpy-1.12.0b1-py3.5-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/opt/packages/python/Python-3.5.2-icc-mkl/lib/python3.5/site-packages/numpy-1.12.0b1-py3.5-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/packages/python/Python-3.5.2-icc-mkl/lib/python3.5/site-packages/numpy-1.12.0b1-py3.5-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/packages/python/Python-3.5.2-icc-mkl/lib/python3.5/site-packages/numpy-1.12.0b1-py3.5-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/packages/python/Python-3.5.2-icc-mkl/lib/python3.5/site-packages/numpy-1.12.0b1-py3.5-linux-x86_64.egg/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

**Comment by bspitzbart** [comment]
'iceberg_seals.tiling --help' works on seawulf
But predicting gives:
(seals) [bspitzbart@login2]$ iceberg_seals.predicting --help
Traceback (most recent call last):
  File "/gpfs/scratch/bspitzbart/seals/bin/iceberg_seals.predicting", line 19, in <module>
    from utils.model_library import *
ModuleNotFoundError: No module named 'utils'
